#!/bin/sh

ME=$(basename "$0")

if [ "$1" = "--help" ]; then
	echo "Create a program that prints whatever is passed as the first"
	echo "argument. The passed argument is guaranteed to be a positive,"
	echo "non-zero integer."
	echo
	echo "In other words, if your program is called like this:"
	echo "  $ME 82"
	echo "then its output should be:"
	echo "  82"
	exit 1
fi

RESULT=$(run/"$ME" 7)

if [ "$RESULT" = "7" ]; then
	touch done/"$ME".done
	exit 0
fi

exit 1
