#!/bin/sh

ME=$(basename "$0")

if [ "$1" = "--help" ]; then
	echo "Create a program that prints 'hello'."
	echo
	exit 1
fi

RESULT=$(run/"$ME" | tr '[:upper:]' '[:lower:]')

if [ "$RESULT" = "hello" ]; then
	touch done/"$ME".done
	exit 0
fi

exit 1
