#!/bin/sh

ME=$(basename "$0")

if [ "$1" = "--help" ]; then
	echo "Create a program that prints the most popular number among 20 integer"
	echo "numbers given as parameters, and how many of those were there."
	echo
	echo "If the given set has more than one most-popular number, the program"
	echo "should print 'invalid set'."
	echo
	echo "You can safely assume only 1-digit numbers will be given."
	echo
	echo "For example, if the program is called like:"
	echo "  $ME 3 7 9 3 5 1 8 7 3 2 9 0 7 1 3 2 5 7 4 3"
	echo "the program should print:"
	echo "  3 5"
	exit 0
fi

RESULT=$(run/"$ME" 3 7 9 3 5 1 8 7 3 2 9 0 7 1 3 2 5 7 4 3)
if [ "$RESULT" != "3 5" ]; then
	exit 1
fi

RESULT=$(run/"$ME" 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9)
if [ "$RESULT" != "invalid set" ]; then
	exit 1
fi

RESULT=$(run/"$ME" 5 7 4 5 6 7 8 6 7 8 9 0 1 7 0 1 2 3 4 9)
if [ "$RESULT" != "7 4" ]; then
	exit 1
fi
