#!/bin/sh

ME=$(basename "$0")

if [ "$1" = "--help" ]; then
	echo "Create a program that takes a numeric first argument and squares"
	echo "it. The passed argument is guaranteed to be a positive integer."
	echo
	exit 1
fi

RESULT=$(run/"$ME" 6)

if [ "$RESULT" = "36" ]; then
	exit 0
fi

exit 1
