#!/bin/sh

ME=$(basename "$0")

if [ "$1" = "--help" ]; then
	echo "Create a program that prints the sum of all the numbers given as"
	echo "arguments from the command line."
	echo
	echo "For example, if the program is called like:"
	echo "  $ME 3 7 9 3 5 1 8 7 3 2 9 0 7 1 3 2 5 7 4 3"
	echo "the program should print:"
	echo "  89"
	exit 0
fi

RESULT=$(run/"$ME" 3 7 9 3 5 1 8 7 3 2 9 0 7 1 3 2 5 7 4 3)
if [ "$RESULT" != "89" ]; then
	exit 1
fi

RESULT=$(run/"$ME" 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9)
if [ "$RESULT" != "90" ]; then
	exit 1
fi

RESULT=$(run/"$ME" 5 7 4 5 6 7 8 6 7 8 9 0 1 7 0 1 2 3 4 9)
if [ "$RESULT" != "99" ]; then
	exit 1
fi
