#!/bin/bash

ME=$(basename $0)

if [ "$1" == "--help" ]; then
	echo "Welcome to TDLPL: Test-Driven Learning Programming Languages."
	echo
	echo "You will be presented with challenges that you should solve in"
	echo "the programming language of your choice. After you attempt to"
	echo "solve the challenge, issue 'make progress' (or just 'make') to"
	echo "continue."
	echo
	echo "When attempting to solve a challenge, name your program after"
	echo "the challenge name you see on the 'Next challenge:' line above."
	echo "Add the appropriate suffix according to the language you are"
	echo "trying to learn. The file should be in the directory you are"
	echo "currently in."
	echo
	echo "For example, to get past this screen, create a file called"
	echo "welcome.py if you are learning Python, or welcome.rb if you are"
	echo "learning Ruby. Consider this to be your first challenge."
	echo
	echo "Good luck!"
	echo
	echo "(BTW, make will always show an 'Error: 1' message. It means that"
	echo "you haven't completed the course. Just ignore it and retry."
	echo
	exit 1
fi

[ -f "run/$ME" ] || exit 1

touch done/$ME.done

exit 0
